Upgrade recalbox.conf : 2nd attempt
recalbox/recalbox-buildroot pull request #484
Opened 2016-09-21 16:19 UTC by substring

Please make sure your PR is ready to be merged !

- [ ] You added the changes in CHANGELOG.md
- [x] You choose the right repository branch to make the PR
- [x] You described the PR as below

Fixes #XXXX

Changes :
This version is now a standalone function in a new .sh
Now it can :
- copy over protected values (like in the wifi password)
- append user defined properties that don't exist by default
- logs in recalbox.log
- property values can have a = inside (like for gamecon), still works
Only drawback : takes about 7s on my pi3. Well, that's once every upgrade, people on the unstable branch will have to cope with it

Please comment and review

2016-09-24 05:33 UTC, digitalLumberjack commented on board/recalbox/fsoverlay/recalbox/scripts/recalbox-includes.sh
> +  savefile=${cfgOut}-pre-$(cat $updVersion)
savefile=${cfgOut}-pre-$(cat $rbxVersion)

2016-09-24 05:33 UTC, digitalLumberjack commented on board/recalbox/fsoverlay/recalbox/scripts/recalbox-includes.sh
> +  updVersion=$_RBX/recalbox.updateversion
This file does not exist.
We already are on the new version as the update has already be done.
We can remove this file.

2016-09-24 05:59 UTC, digitalLumberjack requested changes
Nearly perfect :)

2016-09-24 06:19 UTC, substring commented on board/recalbox/fsoverlay/recalbox/scripts/recalbox-includes.sh
> +  savefile=${cfgOut}-pre-$(cat $updVersion)
would need some string mnipulation as it has afull datetime in it ( some / and : )
In that case, the curVersion var is not necessary either

2016-09-24 07:16 UTC, digitalLumberjack commented on board/recalbox/fsoverlay/recalbox/scripts/recalbox-includes.sh
> +  savefile=${cfgOut}-pre-$(cat $updVersion)
right

2016-09-24 09:31 UTC, substring commented
@digitalLumberjack Changes made as requested. I preferred keeping the `~/logs/logs/lastrecalbox.conf.update` file and the `$curVersion` if the users decided to remove recalbox.conf backups. At least, that way, we manage in a different place the recalbox.conf version

2016-09-25 15:25 UTC, digitalLumberjack commented on board/recalbox/fsoverlay/recalbox/scripts/recalbox-includes.sh
> +    elif containsElement "$name" $forced; then
elif containsElement "$name" "${forced[@]}"; then
Last effort :)

2016-09-25 15:26 UTC, digitalLumberjack requested changes
Just a little change

2016-09-26 05:55 UTC, substring commented
@digitalLumberjack Requested changes were made + slight little improvements. See the commit for details

2016-09-27 13:27 UTC, digitalLumberjack approved these changes
LGTM

2016-09-27 14:29 UTC, substring commented
@nadenislamarre your review would be appreciated pal :)

2016-10-04 19:37 UTC, nadenislamarre commented
sorry, i'm not fan of your shell style as already told.
i've written quickly a similar one in shell, so you can inspire it to update yours, as you prefer.
you can run my example with : ./updateRecalboxConf.sh recalbox.conf.old recalbox.conf

[updaterecalbox.tar.gz](https://github.com/recalbox/recalbox-buildroot/files/509340/updaterecalbox.tar.gz)

2016-10-04 23:04 UTC, substring commented
I like :
- the easier steps (copy the shareinit file to a temp file, look for keys from the share and rewrite them in the temp file)
- much faster
- error handling
- less arrays (which is a consequence of the 1st point)

I don't like :
- you expect some indentation with `[ ]*` as well as some spaces around the `=`.
- you're not using an array for forced values, it would make things easier to maintain and parse
- I don't see the aim of the LAST_KEY. If it's to make a difference in versions, there are much better options
- doesn't replace inline properties that were uncommented, it just writes them at the end of the file (ex : set some wifi SSID and PASS, they are appended instead of replaced)
- missing some logging (ok, that's a quick and dirty version)
- paranoid mode : exits on any error
- it doesn't even make coffe

@digitalLumberjack shall I try to make the best of the 2 scripts ?

2016-10-05 06:59 UTC, nadenislamarre commented
>> you expect some indentation with [ ]* as well as some spaces around the =.
i've not understood. Feel free to put the regular expression that works.

>> you're not using an array for forced values, it would make things easier to maintain and parse
keep it simple.
why make something complicate for something that will probably never evolve ?
more over, in case it evolves, we can change it. Note that if it evolves in a sense that regular expression make more sens, like ps3.*, it can be easier to maintain.
I prefer to make things more complex when they really happend.

>>    I don't see the aim of the LAST_KEY. If it's to make a difference in versions, there are much better options
you didn't want my revision property ;-( so it's just a quick way to check that the file is up to date. When you add values into recalbox.conf, you've to update this value : it's the drawback compared to the revision property.

>>    doesn't replace inline properties that were uncommented, it just writes them at the end of the file (ex : set some wifi SSID and PASS, they are appended instead of replaced)
in fact, i've just tested the file i put in example. So, possibly i don't handle some cases.

>>    paranoid mode : exits on any error
if you check what can cause the error, it's only disk errors or / in values that makes sed fails (because i've not escape them).
I don't find it paranoid, just safe.

>>    it doesn't even make coffe
yes, this was the main target of this script : show what a non java style shell script looks like ;-)

2016-10-16 07:43 UTC, closed without merging