Bump rpi-firmware to ad8608c08b122b2c228dba0ff5070d6e9519faf5 and rpi…
recalbox/recalbox-buildroot pull request #552
Opened 2016-11-10 14:48 UTC by ian57

Please make sure your PR is ready to be merged !

- [ X ] You added the changes in CHANGELOG.md
- [ X ] You choose the right repository branch to make the PR
- [ X] You described the PR as below

Changes :
- Bump rpi-firmware to ad8608c08b122b2c228dba0ff5070d6e9519faf5 and rpi-userland to a1b89e91f393c7134b4cdc36431f863bb3333163 to have the video resolution change on the fly thanks to vcgencmd commande line see https://github.com/raspberrypi/firmware/issues/637
- Useful for pixel perfect on cathodic screen

2016-11-11 07:27 UTC, digitalLumberjack commented
Is this from upstream ?

If we made those changes with custom commits, the next merge with buildroot will be a mess. Best choice would be cherry picking.

2016-11-11 07:28 UTC, digitalLumberjack requested changes
We cannot let only 100mo for graphic memory :)

2016-11-11 07:28 UTC, digitalLumberjack commented on package/rpi-firmware/config.txt
> +gpu_mem_256=100
-gpu_mem_256=128
 -gpu_mem_512=256
 -gpu_mem_1024=512

2016-11-11 07:38 UTC, ian57 commented
Ok, need to tune my PR, sorry, I thought tuning was made with patches for the config.txt.

2016-11-23 10:43 UTC, ian57 commented
Ok I will make another PR using the right method :)

2016-11-23 10:43 UTC, closed without merging