Bump libretro cores
recalbox/recalbox-buildroot pull request #614
Opened 2017-01-14 17:24 UTC by paradadf

Please make sure your PR is ready to be merged !

- [ ] You added the changes in CHANGELOG.md
- [ ] You choose the right repository branch to make the PR
- [ ] You described the PR as below

Fixes #XXXX

Changes :
- Not yet bumped cores are marked under the **Patches?** column. MK files were too different and I din't know what to do.
- libretro-armsnes can be deleted, as the repo doesn't exist anymore.
- The excel sheet has direct links to the relevant repos for easy access.

Related to (put here the others PR in other repositories)
Reference sheet for easy access to the repositories:
[GitHub Repos Libretro + Mupen64Plus.xlsx](https://github.com/recalbox/recalbox-buildroot/files/706089/GitHub.Repos.Libretro.Mupen64Plus.xlsx)

2017-01-14 17:24 UTC, digitalLumberjack commented
Can one of the admins verify this patch?

2017-01-14 17:28 UTC, digitalLumberjack requested changes

2017-01-14 17:28 UTC, digitalLumberjack commented on package/libretro-snes9x-next/libretro-snes9x-next.mk
> +	CFLAGS="$(TARGET_CFLAGS)" CXXFLAGS="$(TARGET_CXXFLAGS)" $(MAKE) CXX="$(TARGET_CXX)" CC="$(TARGET_CC)" -C $(@D)/ -f Makefile.libretro platform="$(LIBRETRO_BOARD)"
Cannot work, rpi1 is not in the list of the Makefile

2017-01-14 17:35 UTC, paradadf commented on package/libretro-snes9x-next/libretro-snes9x-next.mk
> +	CFLAGS="$(TARGET_CFLAGS)" CXXFLAGS="$(TARGET_CXXFLAGS)" $(MAKE) CXX="$(TARGET_CXX)" CC="$(TARGET_CC)" -C $(@D)/ -f Makefile.libretro platform="$(LIBRETRO_BOARD)"
Please, feel free to edit everything! I don't have a clue what to do.

2017-01-22 11:01 UTC, rockaddicted commented
Can be closed, let's continue in https://github.com/recalbox/recalbox-buildroot/pull/644

2017-01-22 11:01 UTC, closed without merging