4.0.1 upgrades and reboots
recalbox/recalbox-buildroot pull request #632
Opened 2017-01-20 22:33 UTC by substring

Please make sure your PR is ready to be merged !

- [ ] You added the changes in CHANGELOG.md
- [x] You choose the right repository branch to make the PR
- [x] You described the PR as below

Fixes #XXXX

Changes :
- can download archives sha1 and verify checksums if available. Won't cancel the update if no .sha1 is found
- install /boot then reboot
- install / then reboot
- tadaaaaaaaaaa upgrade done !

Related to (put here the others PR in other repositories)

2017-01-21 11:38 UTC, digitalLumberjack requested changes

2017-01-21 11:38 UTC, digitalLumberjack commented on board/recalbox/fsoverlay/etc/init.d/S11share
> +        # remove to not apply it indefinitly, even if it fails
just remove the comment, it's not true anymore.

2017-01-21 21:38 UTC, substring commented
@digitalLumberjack added SHA1 checks on recalbox-upgrade and S11, so you can't upgrade with a faulty .tar.xz

2017-01-22 06:56 UTC, digitalLumberjack approved these changes
all right :)

2017-01-22 06:56 UTC, merged