Rb 4.1.x fbcp v2
recalbox/recalbox-buildroot pull request #653
Opened 2017-01-26 10:09 UTC by ian57

Please make sure your PR is ready to be merged !

- [x] You added the changes in CHANGELOG.md
- [x] You choose the right repository branch to make the PR
- [x] You described the PR as below

Changes :
- added the fbcp program to allow display on small tftscreen
- added tft waveshare 3.2 and 3.5 overlays for tft screens

TODO : manegement of the S11fbcp script to run fbcp at start

2017-01-26 11:44 UTC, substring requested changes

2017-01-26 11:44 UTC, substring commented on package/rpi-fbcp/S11fbcp
> +
You should add a `system.fbcp.enabled` (or such a name) in recalbox.conf and do like https://github.com/recalbox/recalbox-buildroot/blob/master/board/recalbox/fsoverlay/etc/init.d/S95api#L13 + https://github.com/recalbox/recalbox-buildroot/blob/master/board/recalbox/fsoverlay/etc/init.d/S95api#L45-L46

2017-01-30 12:59 UTC, ian57 commented on package/rpi-fbcp/S11fbcp
> +
Yep, I know... I think I will bother you with this stuff to get informations about how the configuration works from recalbox.conf to config file such config.txt :)

2017-01-30 17:39 UTC, ian57 commented
Ok fbcp management in recalbox.conf is done.

2017-01-30 17:43 UTC, substring approved these changes

2017-02-09 13:32 UTC, merged

2017-02-09 13:33 UTC, digitalLumberjack commented
Thank you @ian57, @substring